default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: prueba


test:
  <<: *default
  database: Proyecto5_test


production:
  <<: *default
  database: Proyecto5_production
  username: Proyecto5
  password: <%= ENV['PROYECTO5_DATABASE_PASSWORD'] %>
